<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="NC2InGameGuiInputManager\" />
    <Folder Include="NC2MainMenuGuiManager\" />
    <Folder Include="NXSysTime\" />
    <Folder Include="NXSysMouseManager\" />
    <Folder Include="NXSysMisc\" />
    <Folder Include="NXSysKeyManager\" />
    <Folder Include="NXSys2DApp\" />
  </ItemGroup>

</Project>
